version: '3.6'

services:
  kind-chef:
    image: perepadial/kind-chef:alpine-latest
    container_name: 'kind-chef'
    ports:
        - 8090:8090
    expose:
      - 8090
    networks:
      - kind_network

  mongoroot:
    image: mongo:5.0.6-focal
    container_name: 'mongo'
    ports:
      - 27017:27017
    expose:
    - 27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kindchef
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
    networks:
      - kind_network

networks:
  kind_network:
    driver: bridge