on:
  pull_request:

jobs:
  integration-and-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: npm install

      - name: Execute linter
        run: eslint . --ext .js,.jsx,.ts,.tsx
