on:
  pull_request:

jobs:
  integration-and-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup services
        run: docker compose up -d --build

      - name: Prepare environment
        run: npm install

      - name: Execute linter
        run: yarn run eslint . --ext .ts

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash

      - name: Run tests
        run: docker exec kind-chef npm run test
